### ISSUE TITLE
Is there a docker image for arm architecture?

### ISSUE THREAD

**Issue by hugalafutro** [RafhaanShah/Container-Mon#1]
Hi,
I'm currently using Container-mon on my "normal" computers with following compose:
```
version: "3.8"
services:
  container-mon:
    container_name: container-mon
    image: ghcr.io/rafhaanshah/container-mon:latest
    restart: unless-stopped
    environment:
      - DOCKER_HOST=tcp://docker-proxy:2375
      - CONTAINERMON_NOTIFICATION_URL=telegram://${TELE_TOKEN}@telegram?channels=${TELE_ID}
      - CONTAINERMON_CRON=*/2 * * * *
    depends_on:
      - docker-proxy

  docker-proxy:
    container_name: docker_proxy
    image: tecnativa/docker-socket-proxy
    environment:
      - CONTAINERS=1
      - POST=0
    volumes:
      - '/var/run/docker.sock:/var/run/docker.sock'
    ports:
      - 2375:2375
    privileged: true
    restart: unless-stopped
```
but trying to use the same results in exec format error on raspberry pi's for the container-mon container indicating incompatible architecture.

Is there a way to build the docker image on arm architectures? Thanks for any info.
