### ISSUE TITLE
Ntfy notification failing

### ISSUE THREAD

**Issue by juan11perez** [RafhaanShah/Container-Mon#24]
Good day, first thank you for this component.

I'm trying to set up ntfy notifications. I've added the url in line with the instructions in shoutrrr; however, I'm getting the following error:

Error sending notification: unknown service "ntfy"

**Comment by RafhaanShah** [comment]
Hello, can you please paste your confirmation here? (replacing any sensitive info like usernames and passwords)

If possible, could you also try the CLI for Shoutrrr to see if it works there? https://containrrr.dev/shoutrrr/0.7/getting-started/#through_the_cli

**Comment by juan11perez** [comment]
Thank you. Please see below compose

```
  container-mon: 
    container_name: container-mon
    image: ghcr.io/rafhaanshah/container-mon
    restart: unless-stopped
    hostname: UNRAID
    network_mode: appdata_mynet
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    environment:
    - CONTAINERMON_NOTIFICATION_URL=ntfy://user:passwd@myntfy.com/unRAID
    - CONTAINERMON_CRON=*/1 * * * *

```
I'm using very similar URL with watchtower and it's working.

I'm thinking ntfy was added to shoutrr in version 0.7 and container-Mon may not be using that version as last buil was a while back.
