### ISSUE TITLE
[Feature Request] Message parameters (Shoutrrr -> gotify)

### ISSUE THREAD

**Issue by qezzo** [RafhaanShah/Container-Mon#5]
When using shoutrrr to push notifications to gotify the shoutrrr-default title and priority is being used:
![grafik](https://user-images.githubusercontent.com/5079000/199438321-cb714718-3399-42a2-9bfe-232ea6bf608c.png)

The default priority of shoutrrr-gotify is 0 which results in a silent notification. I would like to set a higher priority to actually be notified :)

I tried setting title and priority through CONTAINERMON_NOTIFICATION_URL according to the shoutrrr documentation (https://containrrr.dev/shoutrrr/v0.5/services/gotify/), but container-mon trips over any parameters after the token and quotes.

I think it would be pratical to have a second optional env like CONTAINERMON_NOTIFICATION_PARAMS to set optional parameters.

**Comment by RafhaanShah** [comment]
Hey! Could you give me an example of the URL you tried for Gotify including the parameters?

**Comment by RafhaanShah** [comment]
I just tested it with `export CONTAINERMON_NOTIFICATION_URL="gotify://localhost:8080/TOKEN/?title=Test+Notification&priority=1&disabletls=yes"` and it seems to be sending the notification fine with the title, maybe double check your URL and make sure it's in double quotes when setting the environment variable

**Comment by qezzo** [comment]
Hi, thank you for the quick reply and tests.
I just tested it again and I can't get it working. I tried setting the env in my docker-compose with single quotes, double quotes and each one as param=value and param: value statements.

Here the corresponding logs:
```
CONTAINERMON_NOTIFICATION_URL=gotify://gotify.host.tld:443/<token>/?title=container-mon&priority=5
Starting up Container-Mon
Using config:
  - failure limit: 1
  - cron schedule: */1 * * * *
  - notification service: gotify
  - use labels: false
  - notify when healthy: true
  - check stopped containers: true
Error sending notification: invalid gotify token ""

CONTAINERMON_NOTIFICATION_URL="gotify://gotify.host.tld:443/<token>/?title=container-mon&priority=5"
Starting up Container-Mon
Using config:
  - failure limit: 1
  - cron schedule: */1 * * * *
  - notification service: "gotify
  - use labels: false
  - notify when healthy: true
  - check stopped containers: true
Error sending notification: parse "\"gotify://gotify.host.tld:443/<token>/?title=container-mon&priority=5\"": first path segment in URL cannot contain colon

CONTAINERMON_NOTIFICATION_URL='gotify://gotify.host.tld:443/<token>/?title=container-mon&priority=5'
Starting up Container-Mon
Using config:
  - failure limit: 1
  - cron schedule: */1 * * * *
  - notification service: 'gotify
  - use labels: false
  - notify when healthy: true
  - check stopped containers: true
Error sending notification: parse "'gotify://gotify.host.tld:443/<token>/?title=container-mon&priority=5'": first path segment in URL cannot contain colon

CONTAINERMON_NOTIFICATION_URL: "gotify://gotify.host.tld:443/<token>/?title=container-mon&priority=5"
Starting up Container-Mon
Using config:
  - failure limit: 1
  - cron schedule: */1 * * * *
  - notification service: gotify
  - use labels: false
  - notify when healthy: true
  - check stopped containers: true
Error sending notification: invalid gotify token ""

CONTAINERMON_NOTIFICATION_URL: 'gotify://gotify.host.tld:443/<token>/?title=container-mon&priority=5'
Starting up Container-Mon
Using config:
  - failure limit: 1
  - cron schedule: */1 * * * *
  - notification service: gotify
  - use labels: false
  - notify when healthy: true
  - check stopped containers: true
Error sending notification: invalid gotify token ""
```

I tried exporting the env  like you did with `export CONTAINERMON_NOTIFICATION_URL="gotify://gotify.host.tld:443/<token>/?title=container-mon&priority=5"` in the running container and restarting the app process, but that generated the same error (invalid gotify token "").

**Comment by RafhaanShah** [comment]
Ah you're using `docker-compose`, I think it may be something to do with how YAML does quotes and the environment variables, see:
- https://github.com/containrrr/shoutrrr/issues/45
- https://stackoverflow.com/questions/41988809/docker-compose-how-to-escape-environment-variables

In your `docker-compose.yaml` try these to see if either works:
```
environment:
        - CONTAINERMON_NOTIFICATION_URL=gotify://localhost:8080/TOKEN/?title=Test+Notification&priority=1&disabletls=yes
```

```
environment:
        - "CONTAINERMON_NOTIFICATION_URL=gotify://localhost:8080/TOKEN/?title=Test+Notification&priority=1&disabletls=yes"
```

**Comment by qezzo** [comment]
I tried the shoutrrr cli and it ist working as expected:

![grafik](https://user-images.githubusercontent.com/5079000/199479129-4a0f867b-afdd-4d40-afa5-e7762aac75b0.png)

```
./shoutrrr send --url "gotify://gotify.host.tld:443/<token>/?title=container-mon&priority=5" --message "Test" --verbose
URLs: gotify://gotify.host.tld:443/<token>/?title=container-mon&priority=5
Message: Test
Notification sent

./shoutrrr verify --url "gotify://gotify.host.tld:443/<token>/?title=container-mon&priority=5"
DisableTLS No                                                                                         <Default: No>
Host       gotify.host.tld:443           Server hostname (and optionally port)                        <URL: Host, Port> <Required>
Path                                     Server subpath                                               <URL: Path>
Priority   5                                                                                          <Default: 0>
Title      container-mon                                                                              <Default: Shoutrrr notification>
Token      xxxxxxxxxxxxxxx               Application token                                            <URL: Path> <Required>
```

**Comment by qezzo** [comment]
I just tried your suggestions, the first one was already part of my tests and didn't work. The second one also doesn't work.
Both variants produce the error `Error sending notification: invalid gotify token ""`.

I think the wrong quotation in the compose file results in the error
```
Error sending notification: parse "'gotify://gotify.host.tld:443/<token>/?title=container-mon&priority=5'": first path segment in URL cannot contain colon
```

So I still believe there could be a problem with notification function of Container-Mon. I will install it in go and try getting it to work.

**Comment by qezzo** [comment]
The problem seems to be **portainer** with docker compose.

On a test host it's working fine with docker run and docker compose. But no matter which combination of quotation and escape characters (`?`and `&`) container-mon seems to always forward an incomlete url to shoutrrr, even though `CONTAINERMON_NOTIFICATION_URL` looks correct.

I gave up and now I am using a docker compose outside of portainer (but the same docker host as portainer).

Thank you for your help and this application :)

**Comment by RafhaanShah** [comment]
Oh okay, glad you got it working!

I'll try to have a look into the Portainer issue later on if I get some time, would you mind providing some details about the portainer version and your full `docker-compose` config file you used inside Portainer? Thanks!

**Comment by qezzo** [comment]
I am using the latest Portainer version 2.16.0.
The Docker host is a Debian 10 vm on a Proxmox server.

the container was part of docker-compose with two other services. This is the last version before moving container-mon outside of portainer:
```
version: "2"
services:
  diun:
    image: ghcr.io/crazy-max/diun:latest
    container_name: diun
    hostname: diun-nas
    command: serve
    mem_limit: 64m
    memswap_limit: 64m
    volumes:
      - diun:/data
      - /run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    environment:
      - TZ=Europe/Berlin
      - LOG_LEVEL=info
      - LOG_JSON=false
      - DIUN_WATCH_WORKERS=20
      - "DIUN_WATCH_SCHEDULE=0 */6 * * *"
      - DIUN_PROVIDERS_DOCKER=true
      - DIUN_PROVIDERS_DOCKER_WATCHSTOPPED=false
      - DIUN_PROVIDERS_DOCKER_WATCHBYDEFAULT=false
      - DIUN_NOTIF_GOTIFY_ENDPOINT=http://gotify:80
      - DIUN_NOTIF_GOTIFY_TOKEN=<token>
    labels:
      - "diun.enable=true"
      - "diun.watch_repo=true"
    networks:
      - monitor

  gotify:
    image: gotify/server
    container_name: gotify
    mem_limit: 64m
    memswap_limit: 64m
    volumes:
      - gotify:/app/data
    restart: unless-stopped
    environment:
      - GOTIFY_DEFAULTUSER_NAME=<user>
      - GOTIFY_DEFAULTUSER_PASS=<password>
      - TZ=Europe/Berlin
    ports:
      - 3434:80
    labels:
      - "diun.enable=true"
    networks:
      - monitor

  container-mon:
    image: ghcr.io/rafhaanshah/container-mon:latest
    container_name: container-mon
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - CONTAINERMON_NOTIFICATION_URL=gotify://gotify.host.tld/<token>/?title=container-mon-nas
    labels:
      - "diun.enable=true"
    networks:
      - monitor

volumes:
  diun:
  gotify:

networks:
  monitor:
```

I tested with compose version 3 (memory and swap limits removed), but it didn't change anything. The working solution with standalone docker compose is also using version 2.
